//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.CTDonHangs = new HashSet<CTDonHang>();
        }
    
        [Key]
        [Display(Name = "Mã đơn hàng")]
        public int MaDH { get; set; }

        public Nullable<int> MaKH { get; set; }

        [Display(Name = "Ngày đặt hàng")]
        public Nullable<System.DateTime> NgayDH { get; set; }

        public Nullable<int> MaShip { get; set; }

        [Display(Name = "Địa chỉ nhận hàng")]
        public string DiaChiShip { get; set; }

        [Display(Name = "Trạng thái")]
        public string TrangThai { get; set; }

        [Display(Name = "Ghi chú")]
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDonHang> CTDonHangs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual Ship Ship { get; set; }
    }
}
