//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KhuyenMai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhuyenMai()
        {
            this.LoaiSanPhams = new HashSet<LoaiSanPham>();
        }
    
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Bạn hãy nhập nội dung khuyến mãi")]
        [Display(Name = "Nội dung khuyến mãi")]
        public string NoiDungKM { get; set; }

        [Required(ErrorMessage = "Bạn hãy nhập giá khuyến mãi")]
        [Display(Name = "Giá khuyến mãi")]
        public Nullable<int> GiaKM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoaiSanPham> LoaiSanPhams { get; set; }
    }
}
