//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NhapSanPham
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Bạn hãy nhập mã sản phẩm")]
        [Display(Name = "Mã sản phẩm")]
        public Nullable<int> MaSP { get; set; }

        [Display(Name = "Ngày nhập")]
        public Nullable<System.DateTime> NgayNhap { get; set; }

        [Required(ErrorMessage = "Bạn hãy nhập số lượng")]
        [Display(Name = "Số lượng nhập")]
        public Nullable<int> SoLuong { get; set; }

        [Required(ErrorMessage = "Bạn hãy nhập giá")]
        [Display(Name = "Giá nhập")]
        public Nullable<int> GiaNhap { get; set; }
    }
}
