//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NhapSanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhapSanPham()
        {
            this.CTNhapSanPhams = new HashSet<CTNhapSanPham>();
        }

        [Key]
        [Display(Name = "Mã Đơn Nhập")]
        public int Id { get; set; }

        [Display(Name = "Ngày nhập")]
        public Nullable<System.DateTime> NgayNhap { get; set; }

        public Nullable<int> MaNCC { get; set; }

        public Nullable<int> MaNV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTNhapSanPham> CTNhapSanPhams { get; set; }
    }
}
