//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Review
    {
        [Key]
        [Column(Order = 1)]
        public int MaKH { get; set; }

        [Key]
        [Column(Order = 2)]
        public int MaSP { get; set; }

        [Required(ErrorMessage = "Bạn hãy nhập nội dung")]
        [Display(Name = "Nội dung")]
        public string NoiDung { get; set; }

        [Display(Name = "Ngày tạo")]
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
