//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.CTDonHangs = new HashSet<CTDonHang>();
            this.CTNhapSanPhams = new HashSet<CTNhapSanPham>();
            this.Reviews = new HashSet<Review>();
        }

        [Key]
        [Display(Name = "Mã sản phẩm")]
        public int MaSP { get; set; }

        [Required(ErrorMessage = "Bạn hãy nhập tên sản phẩm")]
        [Display(Name = "Tên sản phẩm")]
        [StringLength(250, ErrorMessage = "{0} phải có từ {2} đến {1} ký tự.", MinimumLength = 3)]
        public string TenSP { get; set; }

        [Required(ErrorMessage = "Bạn hãy nhập giá bán")]
        [Display(Name = "Giá bán")]
        public Nullable<int> Gia { get; set; }

        [Required(ErrorMessage = "Bạn hãy nhập chất liệu")]
        [Display(Name = "Mô tả")]
        public string ChatLieu { get; set; }

        [Required(ErrorMessage = "Bạn hãy nhập kiểu dáng")]
        [Display(Name = "Thôn tin thêm")]
        public string KieuDang { get; set; }

        [Display(Name = "Ảnh")]
        public string LinkAnh { get; set; }

        [Display(Name = "Số lượng")]
        public Nullable<int> SoLuong { get; set; }

        [Display(Name = "Trạng thái xóa")]
        public Nullable<bool> IsDelete { get; set; }

        public Nullable<int> MaNCC { get; set; }
        public Nullable<int> MaLSP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDonHang> CTDonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTNhapSanPham> CTNhapSanPhams { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual NCC NCC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
